"""Builds a .deb package for Card Corner.

    python debpkg/build_deb.py [output_dir]

Depends on system `dpkg-deb` (present on any Debian-family distro, and the
same tool GitHub Actions' ubuntu-latest runners ship). Produces
`<output_dir>/card-corner_<version>_all.deb`. Package layout:

    /usr/share/card-corner/          vendored app source (core/, games/, ui/, main.py, version.py)
    /usr/bin/card-corner              launcher script
    /usr/share/applications/          .desktop entry
    /usr/share/icons/hicolor/256x256/apps/  icon (generated by generate_icon.py)

Pure-Python + Pygame, no compiled extensions of our own, so Architecture is
`all`; Pygame itself comes from the system's python3-pygame package rather
than being vendored, keeping the package small and matching how a normal
apt-installed app pulls its dependencies.
"""
from __future__ import annotations

import shutil
import stat
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from version import __version__  # noqa: E402

PACKAGE_NAME = "card-corner"
ARCHITECTURE = "all"
MAINTAINER = "Card Corner Maintainers <card-corner@users.noreply.github.com>"
DEPENDS = "python3 (>= 3.11), python3-pygame"
DESCRIPTION_SHORT = "Kid-friendly card game suite"
DESCRIPTION_LONG = (
    " Card Corner is a collection of four card games designed for ages\n"
    " 5-8: Go Fish, Old Maid, Memory/Concentration, and Letter Match.\n"
    " Includes computer opponents with three selectable difficulty tiers\n"
    " and a shared launcher."
)

SOURCE_DIRS = ["core", "games", "ui"]
SOURCE_FILES = ["main.py", "version.py"]


def _copy_source(staging: Path) -> None:
    app_dir = staging / "usr" / "share" / PACKAGE_NAME
    app_dir.mkdir(parents=True, exist_ok=True)
    for name in SOURCE_DIRS:
        shutil.copytree(
            REPO_ROOT / name,
            app_dir / name,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
    for name in SOURCE_FILES:
        shutil.copy2(REPO_ROOT / name, app_dir / name)


def _write_launcher(staging: Path) -> None:
    bin_dir = staging / "usr" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    dest = bin_dir / PACKAGE_NAME
    shutil.copy2(REPO_ROOT / "debpkg" / "card-corner.sh", dest)
    dest.chmod(dest.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def _write_desktop_entry(staging: Path) -> None:
    apps_dir = staging / "usr" / "share" / "applications"
    apps_dir.mkdir(parents=True, exist_ok=True)
    # Templated (not copied verbatim) so Exec=/Icon= can never drift out of
    # sync with PACKAGE_NAME / the actual installed launcher script name.
    template = (REPO_ROOT / "debpkg" / "card-corner.desktop").read_text()
    (apps_dir / f"{PACKAGE_NAME}.desktop").write_text(template.format(package_name=PACKAGE_NAME))


def _write_icon(staging: Path) -> None:
    icon_dir = staging / "usr" / "share" / "icons" / "hicolor" / "256x256" / "apps"
    icon_dir.mkdir(parents=True, exist_ok=True)
    icon_path = icon_dir / f"{PACKAGE_NAME}.png"
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "debpkg" / "generate_icon.py"), str(icon_path), "256"],
        check=True,
        env={"SDL_VIDEODRIVER": "dummy", "SDL_AUDIODRIVER": "dummy", "PATH": "/usr/bin:/bin"},
    )


def _write_control(staging: Path, installed_size_kb: int) -> None:
    debian_dir = staging / "DEBIAN"
    debian_dir.mkdir(parents=True, exist_ok=True)
    control = (
        f"Package: {PACKAGE_NAME}\n"
        f"Version: {__version__}\n"
        "Section: games\n"
        "Priority: optional\n"
        f"Architecture: {ARCHITECTURE}\n"
        f"Installed-Size: {installed_size_kb}\n"
        f"Depends: {DEPENDS}\n"
        f"Maintainer: {MAINTAINER}\n"
        f"Description: {DESCRIPTION_SHORT}\n"
        f"{DESCRIPTION_LONG}\n"
    )
    (debian_dir / "control").write_text(control)

    # Best-effort desktop/icon cache refresh; never fail the install over it
    # (e.g. a minimal container image without these tools).
    postinst = (
        "#!/bin/sh\n"
        "set -e\n"
        "command -v update-desktop-database >/dev/null 2>&1 && "
        "update-desktop-database -q /usr/share/applications || true\n"
        "command -v gtk-update-icon-cache >/dev/null 2>&1 && "
        "gtk-update-icon-cache -q /usr/share/icons/hicolor || true\n"
        "exit 0\n"
    )
    postinst_path = debian_dir / "postinst"
    postinst_path.write_text(postinst)
    postinst_path.chmod(0o755)
    (debian_dir / "postrm").write_text(postinst)
    (debian_dir / "postrm").chmod(0o755)


def _set_standard_permissions(staging: Path) -> None:
    for path in staging.rglob("*"):
        if path.is_dir():
            path.chmod(0o755)
        elif path.parent.name == "bin" or path.name in ("postinst", "postrm"):
            path.chmod(0o755)
        else:
            path.chmod(0o644)


def _directory_size_kb(path: Path) -> int:
    total = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
    return max(1, total // 1024)


def build(output_dir: Path) -> Path:
    staging = REPO_ROOT / "build" / "deb-staging"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    _copy_source(staging)
    _write_launcher(staging)
    _write_desktop_entry(staging)
    _write_icon(staging)
    _set_standard_permissions(staging)
    _write_control(staging, _directory_size_kb(staging))
    (staging / "DEBIAN").chmod(0o755)

    output_dir.mkdir(parents=True, exist_ok=True)
    deb_path = output_dir / f"{PACKAGE_NAME}_{__version__}_{ARCHITECTURE}.deb"
    subprocess.run(
        ["dpkg-deb", "--build", "--root-owner-group", str(staging), str(deb_path)],
        check=True,
    )
    return deb_path


if __name__ == "__main__":
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO_ROOT / "dist"
    result = build(out_dir)
    print(f"built {result}")
